FROM htcondor/execute:lts

RUN useradd --uid 2000 --create-home --shell /bin/bash demo
RUN mkdir -p /var/log/condor /var/lib/condor/spool /var/lib/condor/execute /var/lib/condor/lock
RUN chown -R demo:demo /var/log/condor /var/lib/condor/spool /var/lib/condor/execute /var/lib/condor/lock
RUN printf '#!/bin/sh\nexit 0\n' > /usr/libexec/condor_gpu_discovery && chmod 0755 /usr/libexec/condor_gpu_discovery
COPY config/condor_config.worker /etc/condor/condor_config
COPY images/worker-entrypoint.sh /usr/local/bin/worker-entrypoint
RUN chmod 0755 /usr/local/bin/worker-entrypoint
ENTRYPOINT ["/usr/local/bin/worker-entrypoint"]
USER demo
